name: worker_manager
version: 3.1.4
description: Executor allows you to create a queue of tasks for isolate pool
homepage: "https://github.com/Renesanse/worker_manager"

dependencies:
  async: ^2.4.2
  collection: ^1.14.13

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4

environment:
  sdk: ">=2.7.0 <3.0.0"
