name: worker_manager
version: 4.4.1
description: Executor allows you to create a queue of tasks for isolate pool
homepage: "https://github.com/Renesanse/worker_manager"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.8.2
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.3

